# Generated by Django 3.1.1 on 2020-09-22 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 16, 30, 32, 251603, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
